#!/usr/bin/env bash
# Bash script to install and configure Nginx on a new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html

sudo service nginx restart
