#!/usr/bin/env bash
# Script to configure nginx redirection

# Ensure nginx is installed
apt-get update
apt-get install -y nginx

# Configure nginx for redirection
echo "server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

# Restart nginx to apply the changes
service nginx restart
