#!/usr/bin/env bash
# Configures Nginx to respond with a custom header X-Served-By
# shellcheck disable=SC2154
sudo apt-get update
sudo apt-get install -y nginx
echo "server {
  ...
  add_header X-Served-By \$hostname;
  ...
}" | sudo tee /etc/nginx/sites-available/default
sudo systemctl restart nginx
