#!/usr/bin/env bash
# Configures a web server with a custom Nginx response header

# Install Nginx
apt update
apt install -y nginx

# Configure Nginx to add a custom header
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$hostname;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
systemctl restart nginx
