#!/usr/bin/env bash
# Installs and configures HAProxy to balance traffic between two web servers

# Install HAProxy
apt update
apt install -y haproxy

# Configure HAProxy
echo "global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 52.91.151.245:80 check
    server web-02 54.87.217.75:80 check
" > /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
systemctl restart haproxy
