#!/usr/bin/env bash
# This script answers questions about UDP and TCP

# Question 1
echo "It is a protocol that is transferring data in a slow way but surely"

# Question 2
echo "It is a protocol that is transferring data in a fast way and might lose data along in the process"

# Question 3
echo "Have you received boxes x, y, z?"
