#!/usr/bin/env bash

# Insert 'autoindex on;' directive below 'listen 80 default_server' line
sed -i '/listen 80 default_server/ a autoindex on;' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart
