#!/usr/bin/env bash
# This script creates a PID file, displays messages, and handles signals

# Function to handle SIGTERM signal
terminate() {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit
}

# Function to handle SIGINT signal
interrupt() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
quit() {
    echo "Deleting PID file and terminating"
    rm /var/run/myscript.pid
    exit
}

# Register signal handlers
trap terminate SIGTERM
trap interrupt SIGINT
trap quit SIGQUIT

# Create PID file
echo $$ > /var/run/myscript.pid

# Display messages indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
