#!/usr/bin/env bash
# This script displays 'To infinity and beyond' with 'I am invincible!!!' on SIGTERM

sleep() {
  ! read -rt "$1"
} <> <(:)

trap '
  echo "I am invincible!!!"
' TERM

while true
do
  echo 'To infinity and beyond'
  sleep 2
done
