#!/usr/bin/env bash
# This script displays 'To infinity and beyond' with 'I am invincible!!!' on SIGTERM

trap 'echo "I am invincible!!!"; exit' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
