#!/usr/bin/env bash
# This script configures the machine to change the IP address of localhost and facebook.com

# Create a temporary file with modified content
echo "127.0.0.2 localhost" | sudo tee /etc/hosts_temp > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts_temp > /dev/null

# Replace the original /etc/hosts with the modified file
sudo mv /etc/hosts_temp /etc/hosts
