#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Use ifconfig to display active IPv4 IPs
ifconfig -a | awk '/inet / {print $2}' | cut -d':' -f2 | grep -v '127.0.0.1' | tr '\n' ' ' | sed 's/ $//' && echo
