#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080 in 7 lines
sed -i 's/user nginx;/user nginx nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
systemctl restart nginx
