#!/usr/bin/env bash
# This script creates an RSA key pair with a passphrase

# Define the filename for the private key
private_key="school"

# Generate the RSA key pair with the specified parameters
ssh-keygen -t rsa -b 4096 -f ~/.ssh/$private_key -N "betty"

# Print a message indicating the key generation is complete
echo "RSA key pair generation complete."
